# specifies the version of the docker-compose format:
version: '3.8'

# specifies that Docker should use the "bridge
# network driver" for the `inception` network
networks:
  inception:
    driver: bridge

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    env_file: .env
    restart: always
    volumes:
      - 


  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    networks:
      - inception
    env_file: .env
    restart: always
    volumes:
      - 

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    env_file: .env
    restart: always
    volumes:
      - 

volumes: