# specifies the version of the docker-compose format:
version: '3.8'

# specifies that Docker should use the "bridge
# network driver" for the `inception` network
networks:
  inception:
    driver: bridge

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443" # exposes port 443 externally (HTTPS)
    expose:
      - "9000" # exposes port 9000 internally for communication with Wordpress
    depends_on:
      - wordpress
    volumes:
      - 
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    env_file: .env
    networks:
      - inception
    expose:
      - "9000" # exposes port 9000 internally for communication with NGINX
    depends_on:
      - mariadb
    volumes:
      - 
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file: .env
    networks:
      - inception
    expose:
      - "3306" # exposes port 3306 internally for WordPress to communicate
    volumes:
      - 
    restart: always

volumes: