# specifies that Docker should use the default "bridge network driver"
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database-volume:
    driver: local # stores data on the host machine
    driver_opts:
      device: /home/mevangel/data/database-volume # where the volume's data will be stored
      o: bind # uses a "bind mount" which links a specific directory/file on the host machine to the container
      type: none # means no specific filesystem type is enforced
  wordpress-volume:
    driver: local
    driver_opts:
      device: /home/mevangel/data/wordpress-volume
      o: bind
      type: none

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443" # exposes port 443 externally (HTTPS)
    expose:
      - "9000" # exposes port 9000 internally for communication with Wordpress
    depends_on:
      - wordpress
    volumes:
      - wordpress-volume:/var/www/html:ro # shares the wordpress-volume with WordPress (read-only) to serve files
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "9000" # exposes port 9000 internally for communication with NGINX
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed", "--path=/var/www/html"]
      interval: 8s
      timeout: 4s
      retries: 5
    volumes:
      - wordpress-volume:/var/www/html # uses the wordpress-volume volume to store its website files
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "3306" # exposes port 3306 internally for WordPress to communicate
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 8s
      timeout: 4s
      retries: 5
    volumes:
      - database-volume:/var/lib/mysql # uses the database volume for persisting its database files
    restart: always

