# specifies the version of the docker-compose format:
#version: '3.8'

# specifies that Docker should use the default "bridge network driver"
networks:
  inception:
    driver: bridge

volumes:

  database:
    driver: local # stores data on the host machine
    driver_opts:
      o: bind # uses a "bind mount" which links a specific directory/file on the host machine to the container
      type: none # means no specific filesystem type is enforced
      device: /Users/mevangel/data/database # where the volume's data will be stored

  wp_files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/mevangel/data/wp_files

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    env_file: .env
    networks:
      - inception
    expose:
      - "3306" # exposes port 3306 internally for WordPress to communicate
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "mevangel.42.fr"]
    #   interval: 4s
    #   timeout: 3s
    #   retries: 5
    volumes:
      - database:/var/lib/mysql # uses the database volume for persisting its database files
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    env_file: .env
    networks:
      - inception
    expose:
      - "9000" # exposes port 9000 internally for communication with NGINX
    depends_on:
      - mariadb
    #   mariadb:
    #     condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "wp", "core", "is-installed"]
    #   interval: 4s
    #   timeout: 3s
    #   retries: 5
    volumes:
      - wp_files:/var/www/html # uses the wp_files volume to store its website files
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443" # exposes port 443 externally (HTTPS)
    expose:
      - "9000" # exposes port 9000 internally for communication with Wordpress
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://mevangel.42.fr/"]
      interval: 4s
      timeout: 3s
      retries: 5
    volumes:
      - wp_files:/var/www/html:ro # shares the wp_files volume with WordPress (read-only) to serve files
    restart: always
